apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: bot-source
spec:
  source:
    flow: |
      from:
        uri: telegram:bots
        parameters:
          authorizationToken: <the-bot-token>
        steps:
          - set-header:
              name: ce-author
              simple: "${body.from.firstName} ${body.from.lastName}"
          - set-header:
              name: ce-chat
              simple: "${body.chat.id}"
          - set-header:
              name: ce-type
              constant: telegram.bot
          - set-header:
              name: Content-Type
              constant: text/plain
          - transform:
              simple: "${body.text}"
          - to:
              uri: log:info
              parameters:
                showHeaders: true
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
