apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger-bot-echo
spec:
  filter:
    attributes:
      type: telegram.bot
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: echo
