apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger-bot
spec:
  filter:
    attributes:
      type: telegram.bot
      #author: Nicola Ferraro
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: quarkus
