apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger-chuck
spec:
  filter:
    attributes:
      type: chuck.norris
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1beta1
      kind: Service
      name: quarkus
